#-------------------------------------------------------------
# Manifest File to create Deployment with Labels and ReplicaSet
#
# Copyleft (c) byLex 2021
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name:  video-surveillance-site
  labels:
    app  : video-surveillance-site
    env  : prod
    owner: Lex
spec: # з якими подами буде працювати
  replicas: 3
  selector:
    matchLabels:
      project: video-surveillance-site
##############------опис пода------------#####################
  template:
    metadata:
      labels:
        project: video-surveillance-site
    spec: #опис контейнера
      containers:
        - name : cia-web
          image: kuzmyn1983/video-surveillance-site:latest
          ports:
            - containerPort: 80
