#-------------------------------------------------------------
# Manifest File to create Deployment with Labels and AutoScaling
#
# Copyleft (c) by Lex 2021
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: video-surveillance-site-autoscaling
  labels:
    app  : video-surveillance-site
    env  : prod
    owner: Lex
spec:
#  replicas: 2   # Це більше не потрібно, оскільки ми використовуємо HorizontalPodAutoscaler
  selector:
    matchLabels:
      project: video-surveillance-site
  template:
    metadata:
      labels:
        project: video-surveillance-site
    spec:
      containers:
        - name : video-surveillance-site
          image: kuzmyn1983/video-surveillance-site:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-video-surveillance-site
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: video-surveillance-site-autoscaling
  minReplicas: 4
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
