#-------------------------------------------------------------
# Manifest File to create Simple Deployment with Labels
#
# Copyleft (c) by Lex 2021
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment #тип
metadata:
  name: video-surveillance-site
  labels:
    app : video-surveillance-site
spec: # з якими подами буде працювати
  selector:
    matchLabels:
      project: video-surveillance-site
##############------опис пода------------#####################
  template:
    metadata:
      labels:
        project: video-surveillance-site
    spec:
###############-------опис контейнера-----####################      
      containers:
        - name : video-surveillance-site
          image:  kuzmyn1983/video-surveillance-site:latest
          ports:
            - containerPort: 80
###############################################################
